import type { Metadata } from "next";
import { Inter, Manrope, Quattrocento } from "next/font/google";
import "./globals.css";
import { cn } from "@/components/utils";
import localFont from "next/font/local";
import Navbar from "@/components/utils/navbar";
const inter = Inter({ subsets: ["latin"] });
const quattrocento = Quattrocento({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-quattrocento",
});
const manrope = Manrope({
  weight: "400",
  variable: "--font-manrope",
  subsets: ["latin"],
});
const dahlia = localFont({
  src: "../assets/font/dahlia-regular.otf",
  variable: "--font-dahlia",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          manrope.className,
          quattrocento.variable,
          dahlia.variable,
          "text-[#212529] bg-black"
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
