import { AOSInit } from "@/components/shared/aos";
import { cn } from "@/components/utils";
import Navbar from "@/components/utils/navbar";
import type { Metadata } from "next";
import { Inter, Manrope, Quattrocento } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
const quattrocento = Quattrocento({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-quattrocento",
});
const manrope = Manrope({
  weight: "400",
  variable: "--font-manrope",
  subsets: ["latin"],
});
const dahlia = localFont({
  src: "../assets/font/dahlia-regular.otf",
  variable: "--font-dahlia",
});

export const metadata: Metadata = {
  title: "Well Designed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AOSInit />
      <body
        data-aos-easing="linear"
        data-aos-duration="400"
        data-aos-delay="0"
        className={cn(
          manrope.className,
          quattrocento.variable,
          dahlia.variable,
          "bg-black text-[#212529]",
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
